/**
 * 1年生の漢字（80字）の出題語。
 *
 * 日常語を選び、読みだけで漢字が定まらない字には熟語や送り仮名で文脈を付ける
 * （[き] では木/気のどちらか分からないので もく[ようび] / げん[き] とする）。
 * 検証は quiz/kanji/words_test.ts。
 */

import type { KanjiWord } from "../types.ts";

const words: KanjiWord[] = [
  { target: "一", read: "ひと", post: "つ" },
  { target: "七", read: "なな", post: "つ" },
  { target: "三", read: "さん", post: "かく" },
  { target: "上", read: "うえ" },
  { target: "下", read: "した" },
  { target: "中", read: "なか" },
  { target: "九", read: "ここの", post: "つ" },
  { target: "二", read: "ふた", post: "つ" },
  { target: "五", read: "いつ", post: "つ" },
  { target: "人", read: "にん", post: "げん" },
  { target: "休", read: "やす", post: "む" },
  { target: "先", read: "せん", post: "せい" },
  { target: "入", read: "はい", post: "る" },
  { target: "八", read: "はち", post: "じ" },
  { target: "六", read: "ろく", post: "がつ" },
  { target: "円", pre: "ひゃく", read: "えん" },
  { target: "出", read: "で", post: "る" },
  { target: "力", read: "ちから" },
  { target: "十", read: "とお", post: "か" },
  { target: "千", read: "せん", post: "えん" },
  { target: "口", read: "くち" },
  { target: "右", read: "みぎ" },
  { target: "名", read: "な", post: "まえ" },
  { target: "四", read: "し", post: "かく" },
  { target: "土", read: "ど", post: "ようび" },
  { target: "夕", read: "ゆう", post: "がた" },
  { target: "大", read: "おお", post: "きい" },
  { target: "天", read: "てん", post: "き" },
  { target: "女", read: "おんな" },
  { target: "子", read: "こ", post: "ども" },
  { target: "字", pre: "かん", read: "じ" },
  { target: "学", read: "がっ", post: "こう" },
  { target: "小", read: "ちい", post: "さい" },
  { target: "山", read: "やま" },
  { target: "川", read: "かわ" },
  { target: "左", read: "ひだり" },
  { target: "年", read: "とし" },
  { target: "手", read: "て", post: "がみ" },
  { target: "文", pre: "さく", read: "ぶん" },
  { target: "日", read: "にち", post: "ようび" },
  { target: "早", read: "はや", post: "い" },
  { target: "月", read: "げつ", post: "ようび" },
  { target: "木", read: "もく", post: "ようび" },
  { target: "本", read: "ほん" },
  { target: "村", read: "むら" },
  { target: "林", read: "はやし" },
  { target: "校", pre: "がっ", read: "こう" },
  { target: "森", read: "もり" },
  { target: "正", read: "ただ", post: "しい" },
  { target: "気", pre: "げん", read: "き" },
  { target: "水", read: "すい", post: "ようび" },
  { target: "火", read: "か", post: "ようび" },
  { target: "犬", read: "いぬ" },
  { target: "玉", read: "たま" },
  { target: "王", read: "おう", post: "さま" },
  { target: "生", read: "い", post: "きる" },
  { target: "田", read: "た", post: "んぼ" },
  { target: "男", read: "おとこ" },
  { target: "町", read: "まち" },
  { target: "白", read: "しろ", post: "い" },
  { target: "百", read: "ひゃく", post: "えん" },
  { target: "目", read: "め" },
  { target: "石", read: "いし" },
  { target: "空", read: "そら" },
  { target: "立", read: "た", post: "つ" },
  { target: "竹", read: "たけ" },
  { target: "糸", read: "いと" },
  { target: "耳", read: "みみ" },
  { target: "花", read: "はな" },
  { target: "草", read: "くさ" },
  { target: "虫", read: "むし" },
  { target: "見", read: "み", post: "る" },
  { target: "貝", read: "かい" },
  { target: "赤", read: "あか", post: "い" },
  { target: "足", read: "あし" },
  { target: "車", read: "くるま" },
  { target: "金", read: "きん", post: "ようび" },
  { target: "雨", read: "あめ" },
  { target: "青", read: "あお", post: "い" },
  { target: "音", read: "おと" },
];

export default words;
