/**
 * 2年生の漢字（160字）の出題語。方針は 1.ts と同じ。
 */

import type { KanjiWord } from "../types.ts";

const words: KanjiWord[] = [
  { target: "万", read: "まん", post: "えん" },
  { target: "丸", read: "まる", post: "い" },
  { target: "交", read: "こう", post: "つう" },
  { target: "京", pre: "とう", read: "きょう" },
  { target: "今", read: "いま" },
  { target: "会", read: "かい", post: "しゃ" },
  { target: "体", read: "からだ" },
  { target: "何", read: "なに" },
  { target: "作", read: "つく", post: "る" },
  { target: "元", read: "げん", post: "き" },
  { target: "兄", read: "あに" },
  { target: "光", read: "ひか", post: "る" },
  { target: "公", read: "こう", post: "えん" },
  { target: "内", pre: "あん", read: "ない" },
  { target: "冬", read: "ふゆ" },
  { target: "刀", read: "かたな" },
  { target: "分", read: "わ", post: "ける" },
  { target: "切", read: "き", post: "る" },
  { target: "前", read: "まえ" },
  { target: "北", read: "きた" },
  { target: "午", read: "ご", post: "ぜん" },
  { target: "半", read: "はん", post: "ぶん" },
  { target: "南", read: "みなみ" },
  { target: "原", read: "はら", post: "っぱ" },
  { target: "友", read: "とも", post: "だち" },
  { target: "古", read: "ふる", post: "い" },
  { target: "台", read: "だい", post: "どころ" },
  { target: "合", read: "あ", post: "う" },
  { target: "同", read: "おな", post: "じ" },
  { target: "回", read: "まわ", post: "る" },
  { target: "図", pre: "ち", read: "ず" },
  { target: "国", read: "くに" },
  { target: "園", pre: "こう", read: "えん" },
  { target: "地", read: "ち", post: "きゅう" },
  { target: "場", read: "ば", post: "しょ" },
  { target: "声", read: "こえ" },
  { target: "売", read: "う", post: "る" },
  { target: "夏", read: "なつ" },
  { target: "外", read: "そと" },
  { target: "多", read: "おお", post: "い" },
  { target: "夜", read: "よる" },
  { target: "太", read: "ふと", post: "い" },
  { target: "妹", read: "いもうと" },
  { target: "姉", read: "あね" },
  { target: "室", pre: "きょう", read: "しつ" },
  { target: "家", read: "いえ" },
  { target: "寺", read: "てら" },
  { target: "少", read: "すく", post: "ない" },
  { target: "岩", read: "いわ" },
  { target: "工", read: "こう", post: "じょう" },
  { target: "市", read: "いち", post: "ば" },
  { target: "帰", read: "かえ", post: "る" },
  { target: "広", read: "ひろ", post: "い" },
  { target: "店", read: "みせ" },
  { target: "弓", read: "ゆみ" },
  { target: "引", read: "ひ", post: "く" },
  { target: "弟", read: "おとうと" },
  { target: "弱", read: "よわ", post: "い" },
  { target: "強", read: "つよ", post: "い" },
  { target: "当", read: "あ", post: "たる" },
  { target: "形", read: "かたち" },
  { target: "後", read: "うし", post: "ろ" },
  { target: "心", read: "こころ" },
  { target: "思", read: "おも", post: "う" },
  { target: "戸", read: "と", post: "だな" },
  { target: "才", pre: "てん", read: "さい" },
  { target: "教", read: "おし", post: "える" },
  { target: "数", read: "かず" },
  { target: "新", read: "あたら", post: "しい" },
  { target: "方", pre: "ゆう", read: "がた" },
  { target: "明", read: "あか", post: "るい" },
  { target: "星", read: "ほし" },
  { target: "春", read: "はる" },
  { target: "昼", read: "ひる" },
  { target: "時", read: "とき" },
  { target: "晴", read: "は", post: "れる" },
  { target: "曜", read: "よう", post: "び" },
  { target: "書", read: "か", post: "く" },
  { target: "朝", read: "あさ" },
  { target: "来", read: "く", post: "る" },
  { target: "東", read: "とう", post: "きょう" },
  { target: "楽", read: "たの", post: "しい" },
  { target: "歌", read: "うた" },
  { target: "止", read: "と", post: "まる" },
  { target: "歩", read: "ある", post: "く" },
  { target: "母", read: "はは" },
  { target: "毎", read: "まい", post: "にち" },
  { target: "毛", read: "け" },
  { target: "池", read: "いけ" },
  { target: "汽", read: "き", post: "しゃ" },
  { target: "活", pre: "せい", read: "かつ" },
  { target: "海", read: "うみ" },
  { target: "点", read: "てん", post: "すう" },
  { target: "父", read: "ちち" },
  { target: "牛", read: "うし" },
  { target: "理", read: "り", post: "ゆう" },
  { target: "用", read: "よう", post: "じ" },
  { target: "画", pre: "えい", read: "が" },
  { target: "番", read: "ばん", post: "ごう" },
  { target: "直", read: "なお", post: "す" },
  { target: "矢", read: "や", post: "じるし" },
  { target: "知", read: "し", post: "る" },
  { target: "社", pre: "かい", read: "しゃ" },
  { target: "秋", read: "あき" },
  { target: "科", read: "か", post: "がく" },
  { target: "答", read: "こた", post: "える" },
  { target: "算", read: "さん", post: "すう" },
  { target: "米", read: "こめ" },
  { target: "紙", read: "かみ" },
  { target: "細", read: "ほそ", post: "い" },
  { target: "組", read: "くみ" },
  { target: "絵", read: "え" },
  { target: "線", read: "せん", post: "ろ" },
  { target: "羽", read: "はね" },
  { target: "考", read: "かんが", post: "える" },
  { target: "聞", read: "き", post: "く" },
  { target: "肉", read: "にく" },
  { target: "自", read: "じ", post: "てんしゃ" },
  { target: "船", read: "ふね" },
  { target: "色", read: "いろ" },
  { target: "茶", read: "ちゃ", post: "いろ" },
  { target: "行", read: "い", post: "く" },
  { target: "西", read: "にし" },
  { target: "親", read: "おや" },
  { target: "角", read: "かど" },
  { target: "言", read: "い", post: "う" },
  { target: "計", read: "けい", post: "さん" },
  { target: "記", read: "き", post: "ろく" },
  { target: "話", read: "はな", post: "す" },
  { target: "語", pre: "こく", read: "ご" },
  { target: "読", read: "よ", post: "む" },
  { target: "谷", read: "たに" },
  { target: "買", read: "か", post: "う" },
  { target: "走", read: "はし", post: "る" },
  { target: "近", read: "ちか", post: "い" },
  { target: "通", read: "とお", post: "る" },
  { target: "週", read: "しゅう", post: "まつ" },
  { target: "道", read: "みち" },
  { target: "遠", read: "とお", post: "い" },
  { target: "里", read: "さと" },
  { target: "野", read: "の", post: "はら" },
  { target: "長", read: "なが", post: "い" },
  { target: "門", read: "もん" },
  { target: "間", read: "あいだ" },
  { target: "雪", read: "ゆき" },
  { target: "雲", read: "くも" },
  { target: "電", read: "でん", post: "わ" },
  { target: "頭", read: "あたま" },
  { target: "顔", read: "かお" },
  { target: "風", read: "かぜ" },
  { target: "食", read: "た", post: "べる" },
  { target: "首", read: "くび" },
  { target: "馬", read: "うま" },
  { target: "高", read: "たか", post: "い" },
  { target: "魚", read: "さかな" },
  { target: "鳥", read: "とり" },
  { target: "鳴", read: "な", post: "く" },
  { target: "麦", read: "むぎ" },
  { target: "黄", read: "き", post: "いろ" },
  { target: "黒", read: "くろ", post: "い" },
];

export default words;
