/**
 * 3年生の漢字（200字）の出題語。方針は 1.ts と同じ。
 */

import type { KanjiWord } from "../types.ts";

const words: KanjiWord[] = [
  { target: "丁", read: "ちょう", post: "め" },
  { target: "世", read: "せ", post: "かい" },
  { target: "両", read: "りょう", post: "て" },
  { target: "主", read: "しゅ", post: "じん" },
  { target: "乗", read: "の", post: "る" },
  { target: "予", read: "よ", post: "てい" },
  { target: "事", read: "こと" },
  { target: "仕", read: "し", post: "ごと" },
  { target: "他", read: "ほか" },
  { target: "代", pre: "じ", read: "だい" },
  { target: "住", read: "す", post: "む" },
  { target: "使", read: "つか", post: "う" },
  { target: "係", read: "かかり", post: "いん" },
  { target: "倍", read: "ばい" },
  { target: "全", read: "ぜん", post: "ぶ" },
  { target: "具", pre: "どう", read: "ぐ" },
  { target: "写", read: "うつ", post: "す" },
  { target: "列", read: "れつ" },
  { target: "助", read: "たす", post: "ける" },
  { target: "勉", read: "べん", post: "きょう" },
  { target: "動", read: "うご", post: "く" },
  { target: "勝", read: "か", post: "つ" },
  { target: "化", pre: "へん", read: "か" },
  { target: "区", pre: "ち", read: "く" },
  { target: "医", read: "い", post: "しゃ" },
  { target: "去", read: "きょ", post: "ねん" },
  { target: "反", read: "はん", post: "たい" },
  { target: "取", read: "と", post: "る" },
  { target: "受", read: "う", post: "ける" },
  { target: "号", pre: "ばん", read: "ごう" },
  { target: "向", read: "む", post: "く" },
  { target: "君", read: "きみ" },
  { target: "味", read: "あじ" },
  { target: "命", read: "いのち" },
  { target: "和", pre: "へい", read: "わ" },
  { target: "品", read: "しな", post: "もの" },
  { target: "員", pre: "てん", read: "いん" },
  { target: "商", read: "しょう", post: "てん" },
  { target: "問", read: "もん", post: "だい" },
  { target: "坂", read: "さか", post: "みち" },
  { target: "央", pre: "ちゅう", read: "おう" },
  { target: "始", read: "はじ", post: "める" },
  { target: "委", read: "い", post: "いんかい" },
  { target: "守", read: "まも", post: "る" },
  { target: "安", read: "やす", post: "い" },
  { target: "定", pre: "よ", read: "てい" },
  { target: "実", read: "じっ", post: "けん" },
  { target: "客", read: "きゃく" },
  { target: "宮", read: "みや" },
  { target: "宿", read: "しゅく", post: "だい" },
  { target: "寒", read: "さむ", post: "い" },
  { target: "対", pre: "はん", read: "たい" },
  { target: "局", read: "きょく" },
  { target: "屋", read: "や", post: "ね" },
  { target: "岸", read: "きし" },
  { target: "島", read: "しま" },
  { target: "州", pre: "ほん", read: "しゅう" },
  { target: "帳", pre: "て", read: "ちょう" },
  { target: "平", read: "たい", post: "ら" },
  { target: "幸", read: "しあわ", post: "せ" },
  { target: "度", pre: "おん", read: "ど" },
  { target: "庫", pre: "そう", read: "こ" },
  { target: "庭", read: "にわ" },
  { target: "式", read: "しき" },
  { target: "役", read: "やく", post: "しゃ" },
  { target: "待", read: "ま", post: "つ" },
  { target: "急", read: "いそ", post: "ぐ" },
  { target: "息", read: "いき" },
  { target: "悪", read: "わる", post: "い" },
  { target: "悲", read: "かな", post: "しい" },
  { target: "想", read: "そう", post: "ぞう" },
  { target: "意", read: "い", post: "み" },
  { target: "感", read: "かん", post: "じる" },
  { target: "所", read: "ところ" },
  { target: "打", read: "う", post: "つ" },
  { target: "投", read: "な", post: "げる" },
  { target: "拾", read: "ひろ", post: "う" },
  { target: "持", read: "も", post: "つ" },
  { target: "指", read: "ゆび" },
  { target: "放", read: "ほう", post: "そう" },
  { target: "整", read: "ととの", post: "える" },
  { target: "旅", read: "たび" },
  { target: "族", pre: "か", read: "ぞく" },
  { target: "昔", read: "むかし" },
  { target: "昭", read: "しょう", post: "わ" },
  { target: "暑", read: "あつ", post: "い" },
  { target: "暗", read: "くら", post: "い" },
  { target: "曲", read: "ま", post: "がる" },
  { target: "有", read: "ゆう", post: "めい" },
  { target: "服", read: "ふく" },
  { target: "期", pre: "がっ", read: "き" },
  { target: "板", read: "いた" },
  { target: "柱", read: "はしら" },
  { target: "根", pre: "や", read: "ね" },
  { target: "植", read: "う", post: "える" },
  { target: "業", pre: "じゅ", read: "ぎょう" },
  { target: "様", read: "さま" },
  { target: "横", read: "よこ" },
  { target: "橋", read: "はし" },
  { target: "次", read: "つぎ" },
  { target: "歯", read: "は" },
  { target: "死", read: "し", post: "ぬ" },
  { target: "氷", read: "こおり" },
  { target: "決", read: "き", post: "める" },
  { target: "油", read: "あぶら" },
  { target: "波", read: "なみ" },
  { target: "注", read: "ちゅう", post: "い" },
  { target: "泳", read: "およ", post: "ぐ" },
  { target: "洋", read: "よう", post: "ふく" },
  { target: "流", read: "なが", post: "れる" },
  { target: "消", read: "け", post: "す" },
  { target: "深", read: "ふか", post: "い" },
  { target: "温", read: "あたた", post: "かい" },
  { target: "港", read: "みなと" },
  { target: "湖", read: "みずうみ" },
  { target: "湯", read: "ゆ" },
  { target: "漢", read: "かん", post: "じ" },
  { target: "炭", read: "すみ" },
  { target: "物", read: "もの" },
  { target: "球", pre: "ち", read: "きゅう" },
  { target: "由", pre: "り", read: "ゆう" },
  { target: "申", read: "もう", post: "す" },
  { target: "界", pre: "せ", read: "かい" },
  { target: "畑", read: "はたけ" },
  { target: "病", read: "びょう", post: "き" },
  { target: "発", read: "はっ", post: "けん" },
  { target: "登", read: "のぼ", post: "る" },
  { target: "皮", pre: "け", read: "がわ" },
  { target: "皿", read: "さら" },
  { target: "相", read: "あい", post: "て" },
  { target: "県", read: "けん" },
  { target: "真", pre: "しゃ", read: "しん" },
  { target: "着", read: "き", post: "もの" },
  { target: "短", read: "みじか", post: "い" },
  { target: "研", read: "けん", post: "きゅう" },
  { target: "礼", read: "れい" },
  { target: "神", read: "かみ", post: "さま" },
  { target: "祭", read: "まつ", post: "り" },
  { target: "福", pre: "こう", read: "ふく" },
  { target: "秒", read: "びょう" },
  { target: "究", pre: "けん", read: "きゅう" },
  { target: "章", pre: "ぶん", read: "しょう" },
  { target: "童", read: "どう", post: "わ" },
  { target: "笛", read: "ふえ" },
  { target: "第", read: "だい", post: "いち" },
  { target: "筆", read: "ふで" },
  { target: "等", read: "とう" },
  { target: "箱", read: "はこ" },
  { target: "級", pre: "がっ", read: "きゅう" },
  { target: "終", read: "お", post: "わる" },
  { target: "緑", read: "みどり" },
  { target: "練", read: "れん", post: "しゅう" },
  { target: "羊", read: "ひつじ" },
  { target: "美", read: "うつく", post: "しい" },
  { target: "習", pre: "れん", read: "しゅう" },
  { target: "者", pre: "い", read: "しゃ" },
  { target: "育", read: "そだ", post: "てる" },
  { target: "苦", read: "くる", post: "しい" },
  { target: "荷", read: "に", post: "もつ" },
  { target: "落", read: "お", post: "ちる" },
  { target: "葉", read: "は", post: "っぱ" },
  { target: "薬", read: "くすり" },
  { target: "血", read: "ち" },
  { target: "表", read: "おもて" },
  { target: "詩", read: "し" },
  { target: "調", read: "しら", post: "べる" },
  { target: "談", pre: "そう", read: "だん" },
  { target: "豆", read: "まめ" },
  { target: "負", read: "ま", post: "ける" },
  { target: "起", read: "お", post: "きる" },
  { target: "路", pre: "せん", read: "ろ" },
  { target: "身", read: "み" },
  { target: "転", read: "ころ", post: "ぶ" },
  { target: "軽", read: "かる", post: "い" },
  { target: "農", read: "のう", post: "か" },
  { target: "返", read: "かえ", post: "す" },
  { target: "追", read: "お", post: "う" },
  { target: "送", pre: "ほう", read: "そう" },
  { target: "速", read: "そく", post: "ど" },
  { target: "進", read: "すす", post: "む" },
  { target: "遊", read: "あそ", post: "ぶ" },
  { target: "運", read: "うん", post: "どう" },
  { target: "部", read: "ぶ", post: "ぶん" },
  { target: "都", read: "と", post: "かい" },
  { target: "配", read: "くば", post: "る" },
  { target: "酒", read: "さけ" },
  { target: "重", read: "おも", post: "い" },
  { target: "鉄", read: "てつ" },
  { target: "銀", read: "ぎん", post: "こう" },
  { target: "開", read: "あ", post: "ける" },
  { target: "院", pre: "びょう", read: "いん" },
  { target: "陽", pre: "たい", read: "よう" },
  { target: "階", read: "かい", post: "だん" },
  { target: "集", read: "あつ", post: "める" },
  { target: "面", read: "めん" },
  { target: "題", pre: "もん", read: "だい" },
  { target: "飲", read: "の", post: "む" },
  { target: "館", pre: "としょ", read: "かん" },
  { target: "駅", read: "えき" },
  { target: "鼻", read: "はな", post: "みず" },
];

export default words;
