/**
 * 4年生の漢字（220字）の出題語。方針は 1.ts と同じ。
 * 都道府県名の漢字（2020年度改訂で第4学年に加わった20字）は県名で出題する。
 */

import type { KanjiWord } from "../types.ts";

const words: KanjiWord[] = [
  { target: "不", read: "ふ", post: "しぎ" },
  { target: "争", read: "あらそ", post: "う" },
  { target: "井", read: "い", post: "ど" },
  { target: "付", read: "つ", post: "ける" },
  { target: "令", pre: "めい", read: "れい" },
  { target: "以", read: "い", post: "じょう" },
  { target: "仲", read: "なか", post: "よし" },
  { target: "伝", read: "つた", post: "える" },
  { target: "位", read: "くらい" },
  { target: "低", read: "ひく", post: "い" },
  { target: "佐", read: "さ", post: "がけん" },
  { target: "例", read: "たと", post: "える" },
  { target: "便", read: "べん", post: "り" },
  { target: "信", read: "しん", post: "じる" },
  { target: "倉", read: "そう", post: "こ" },
  { target: "候", pre: "き", read: "こう" },
  { target: "借", read: "か", post: "りる" },
  { target: "停", read: "てい", post: "しゃ" },
  { target: "健", read: "けん", post: "こう" },
  { target: "側", read: "がわ" },
  { target: "働", read: "はたら", post: "く" },
  { target: "億", read: "おく" },
  { target: "兆", read: "ちょう" },
  { target: "児", read: "じ", post: "どう" },
  { target: "共", read: "とも" },
  { target: "兵", read: "へい", post: "たい" },
  { target: "典", pre: "じ", read: "てん" },
  { target: "冷", read: "つめ", post: "たい" },
  { target: "初", read: "はじ", post: "めて" },
  { target: "別", read: "わか", post: "れる" },
  { target: "利", pre: "べん", read: "り" },
  { target: "刷", pre: "いん", read: "さつ" },
  { target: "副", read: "ふく", post: "さよう" },
  { target: "功", pre: "せい", read: "こう" },
  { target: "加", read: "くわ", post: "える" },
  { target: "努", read: "つと", post: "める" },
  { target: "労", read: "ろう", post: "どう" },
  { target: "勇", read: "ゆう", post: "き" },
  { target: "包", read: "つつ", post: "む" },
  { target: "卒", read: "そつ", post: "ぎょう" },
  { target: "協", read: "きょう", post: "りょく" },
  { target: "単", read: "たん", post: "ご" },
  { target: "博", read: "はく", post: "ぶつかん" },
  { target: "印", read: "いん", post: "さつ" },
  { target: "参", read: "さん", post: "か" },
  { target: "史", pre: "れき", read: "し" },
  { target: "司", read: "し", post: "かい" },
  { target: "各", read: "かく", post: "ち" },
  { target: "告", pre: "ほう", read: "こく" },
  { target: "周", read: "まわ", post: "り" },
  { target: "唱", pre: "がっ", read: "しょう" },
  { target: "喜", read: "よろこ", post: "ぶ" },
  { target: "器", pre: "しょっ", read: "き" },
  { target: "囲", read: "かこ", post: "む" },
  { target: "固", read: "かた", post: "い" },
  { target: "型", read: "かた" },
  { target: "埼", read: "さい", post: "たまけん" },
  { target: "堂", pre: "しょく", read: "どう" },
  { target: "塩", read: "しお" },
  { target: "士", pre: "ぶ", read: "し" },
  { target: "変", read: "か", post: "わる" },
  { target: "夫", read: "おっと" },
  { target: "失", read: "うしな", post: "う" },
  { target: "奈", read: "な", post: "らけん" },
  { target: "好", read: "す", post: "き" },
  { target: "媛", pre: "え", read: "ひめ", post: "けん" },
  { target: "季", read: "き", post: "せつ" },
  { target: "孫", read: "まご" },
  { target: "完", read: "かん", post: "せい" },
  { target: "官", pre: "けい", read: "かん" },
  { target: "害", pre: "こう", read: "がい" },
  { target: "察", pre: "けい", read: "さつ" },
  { target: "岐", read: "ぎ", post: "ふけん" },
  { target: "岡", pre: "しず", read: "おか", post: "けん" },
  { target: "崎", pre: "なが", read: "さき", post: "けん" },
  { target: "巣", read: "す" },
  { target: "差", read: "さ" },
  { target: "希", read: "き", post: "ぼう" },
  { target: "席", read: "せき" },
  { target: "帯", read: "おび" },
  { target: "底", read: "そこ" },
  { target: "府", pre: "きょうと", read: "ふ" },
  { target: "康", pre: "けん", read: "こう" },
  { target: "建", read: "た", post: "てる" },
  { target: "径", pre: "はん", read: "けい" },
  { target: "徒", pre: "せい", read: "と" },
  { target: "得", read: "とく", post: "い" },
  { target: "必", read: "かなら", post: "ず" },
  { target: "念", read: "ねん" },
  { target: "愛", read: "あい" },
  { target: "成", read: "せい", post: "こう" },
  { target: "戦", read: "たたか", post: "う" },
  { target: "折", read: "お", post: "る" },
  { target: "挙", read: "あ", post: "げる" },
  { target: "改", read: "あらた", post: "める" },
  { target: "救", read: "すく", post: "う" },
  { target: "敗", pre: "しっ", read: "ぱい" },
  { target: "散", read: "ち", post: "る" },
  { target: "料", read: "りょう", post: "り" },
  { target: "旗", read: "はた" },
  { target: "昨", read: "さく", post: "ねん" },
  { target: "景", pre: "ふう", read: "けい" },
  { target: "最", read: "もっと", post: "も" },
  { target: "望", pre: "き", read: "ぼう" },
  { target: "未", read: "み", post: "らい" },
  { target: "末", pre: "しゅう", read: "まつ" },
  { target: "札", read: "ふだ" },
  { target: "材", read: "ざい", post: "りょう" },
  { target: "束", read: "たば" },
  { target: "松", read: "まつ" },
  { target: "果", pre: "けっ", read: "か" },
  { target: "栃", read: "とち", post: "ぎけん" },
  { target: "栄", read: "さか", post: "える" },
  { target: "案", read: "あん", post: "ない" },
  { target: "梅", read: "うめ" },
  { target: "梨", read: "なし" },
  { target: "械", pre: "き", read: "かい" },
  { target: "極", pre: "なん", read: "きょく" },
  { target: "標", pre: "もく", read: "ひょう" },
  { target: "機", pre: "ひこう", read: "き" },
  { target: "欠", read: "か", post: "ける" },
  { target: "歴", read: "れき", post: "し" },
  { target: "残", read: "のこ", post: "る" },
  { target: "殺", read: "ころ", post: "す" },
  { target: "毒", read: "どく" },
  { target: "氏", read: "し", post: "めい" },
  { target: "民", pre: "こく", read: "みん" },
  { target: "求", read: "もと", post: "める" },
  { target: "沖", read: "おき", post: "なわけん" },
  { target: "治", read: "なお", post: "る" },
  { target: "法", read: "ほう", post: "りつ" },
  { target: "泣", read: "な", post: "きむし" },
  { target: "浅", read: "あさ", post: "い" },
  { target: "浴", read: "あ", post: "びる" },
  { target: "清", read: "きよ", post: "い" },
  { target: "満", read: "み", post: "ちる" },
  { target: "滋", read: "し", post: "がけん" },
  { target: "漁", read: "ぎょ", post: "せん" },
  { target: "潟", pre: "にい", read: "がた", post: "けん" },
  { target: "灯", read: "とう", post: "だい" },
  { target: "無", read: "む", post: "り" },
  { target: "然", pre: "し", read: "ぜん" },
  { target: "焼", read: "や", post: "く" },
  { target: "照", read: "て", post: "らす" },
  { target: "熊", read: "くま", post: "もとけん" },
  { target: "熱", read: "ねっ", post: "しん" },
  { target: "牧", read: "ぼく", post: "じょう" },
  { target: "特", read: "とく", post: "べつ" },
  { target: "産", read: "さん", post: "ぎょう" },
  { target: "的", pre: "もく", read: "てき" },
  { target: "省", read: "はぶ", post: "く" },
  { target: "祝", read: "いわ", post: "う" },
  { target: "票", pre: "とう", read: "ひょう" },
  { target: "種", read: "たね" },
  { target: "積", read: "つ", post: "もる" },
  { target: "競", read: "きそ", post: "う" },
  { target: "笑", read: "わら", post: "う" },
  { target: "管", read: "くだ" },
  { target: "節", read: "ふし" },
  { target: "粉", read: "こな" },
  { target: "紀", pre: "せい", read: "き" },
  { target: "約", read: "やく", post: "そく" },
  { target: "結", read: "むす", post: "ぶ" },
  { target: "給", read: "きゅう", post: "しょく" },
  { target: "続", read: "つづ", post: "く" },
  { target: "縄", read: "なわ", post: "とび" },
  { target: "置", read: "お", post: "く" },
  { target: "老", read: "お", post: "いる" },
  { target: "胃", read: "い" },
  { target: "脈", read: "みゃく" },
  { target: "腸", pre: "い", read: "ちょう" },
  { target: "臣", pre: "だい", read: "じん" },
  { target: "航", read: "こう", post: "かい" },
  { target: "良", read: "よ", post: "い" },
  { target: "芸", read: "げい", post: "じゅつ" },
  { target: "芽", read: "め", post: "ばえ" },
  { target: "英", read: "えい", post: "ご" },
  { target: "茨", read: "いばら", post: "きけん" },
  { target: "菜", pre: "や", read: "さい" },
  { target: "街", pre: "しょうてん", read: "がい" },
  { target: "衣", read: "い", post: "ふく" },
  { target: "要", pre: "ひつ", read: "よう" },
  { target: "覚", read: "おぼ", post: "える" },
  { target: "観", read: "かん", post: "さつ" },
  { target: "訓", read: "くん", post: "れん" },
  { target: "試", read: "ため", post: "す" },
  { target: "説", read: "せつ", post: "めい" },
  { target: "課", pre: "ほう", read: "か", post: "ご" },
  { target: "議", pre: "かい", read: "ぎ" },
  { target: "象", read: "ぞう" },
  { target: "貨", read: "か", post: "もつ" },
  { target: "貯", read: "ちょ", post: "きん" },
  { target: "費", read: "ひ", post: "よう" },
  { target: "賞", read: "しょう" },
  { target: "軍", read: "ぐん", post: "たい" },
  { target: "輪", read: "わ" },
  { target: "辞", read: "じ", post: "しょ" },
  { target: "辺", read: "あた", post: "り" },
  { target: "連", read: "つ", post: "れる" },
  { target: "達", pre: "とも", read: "だち" },
  { target: "選", read: "えら", post: "ぶ" },
  { target: "郡", read: "ぐん", post: "ぶ" },
  { target: "量", read: "りょう" },
  { target: "録", pre: "き", read: "ろく" },
  { target: "鏡", read: "かがみ" },
  { target: "関", read: "かん", post: "けい" },
  { target: "阜", pre: "ぎ", read: "ふ", post: "けん" },
  { target: "阪", pre: "おお", read: "さか", post: "ふ" },
  { target: "陸", read: "りく" },
  { target: "隊", pre: "へい", read: "たい" },
  { target: "静", read: "しず", post: "か" },
  { target: "順", read: "じゅん", post: "ばん" },
  { target: "願", read: "ねが", post: "う" },
  { target: "類", pre: "しゅ", read: "るい" },
  { target: "飛", read: "と", post: "ぶ" },
  { target: "飯", pre: "ご", read: "はん" },
  { target: "養", read: "やしな", post: "う" },
  { target: "香", read: "か", post: "がわけん" },
  { target: "験", pre: "じっ", read: "けん" },
  { target: "鹿", read: "か", post: "ごしまけん" },
];

export default words;
