/**
 * 5年生の漢字（185字）の出題語。方針は 1.ts と同じ。
 */

import type { KanjiWord } from "../types.ts";

const words: KanjiWord[] = [
  { target: "久", read: "ひさ", post: "しぶり" },
  { target: "仏", read: "ほとけ" },
  { target: "仮", read: "かり" },
  { target: "件", pre: "じ", read: "けん" },
  { target: "任", read: "まか", post: "せる" },
  { target: "似", read: "に", post: "る" },
  { target: "余", read: "あま", post: "る" },
  { target: "価", read: "か", post: "かく" },
  { target: "保", read: "たも", post: "つ" },
  { target: "修", read: "しゅう", post: "り" },
  { target: "俵", read: "たわら" },
  { target: "個", read: "こ", post: "じん" },
  { target: "備", read: "そな", post: "える" },
  { target: "像", pre: "そう", read: "ぞう" },
  { target: "再", read: "ふたた", post: "び" },
  { target: "刊", pre: "ちょう", read: "かん" },
  { target: "判", read: "はん", post: "だん" },
  { target: "制", read: "せい", post: "ふく" },
  { target: "券", pre: "にゅうじょう", read: "けん" },
  { target: "則", pre: "き", read: "そく" },
  { target: "効", read: "こう", post: "か" },
  { target: "務", pre: "ぎ", read: "む" },
  { target: "勢", read: "いきお", post: "い" },
  { target: "厚", read: "あつ", post: "がみ" },
  { target: "句", pre: "はい", read: "く" },
  { target: "可", read: "か", post: "のう" },
  { target: "営", read: "いとな", post: "む" },
  { target: "因", pre: "げん", read: "いん" },
  { target: "団", pre: "しゅう", read: "だん" },
  { target: "圧", read: "あつ", post: "りょく" },
  { target: "在", pre: "げん", read: "ざい" },
  { target: "均", pre: "へい", read: "きん" },
  { target: "基", read: "き", post: "ほん" },
  { target: "報", read: "ほう", post: "こく" },
  { target: "境", read: "さかい" },
  { target: "墓", read: "はか" },
  { target: "増", read: "ふ", post: "える" },
  { target: "夢", read: "ゆめ" },
  { target: "妻", read: "つま" },
  { target: "婦", read: "ふ", post: "じん" },
  { target: "容", pre: "ない", read: "よう" },
  { target: "寄", read: "よ", post: "る" },
  { target: "富", read: "とみ" },
  { target: "導", read: "みちび", post: "く" },
  { target: "居", read: "い", post: "る" },
  { target: "属", pre: "きん", read: "ぞく" },
  { target: "布", read: "ぬの" },
  { target: "師", pre: "きょう", read: "し" },
  { target: "常", read: "つね" },
  { target: "幹", pre: "しん", read: "かん", post: "せん" },
  { target: "序", pre: "じゅん", read: "じょ" },
  { target: "弁", read: "べん", post: "とう" },
  { target: "張", read: "は", post: "る" },
  { target: "往", read: "おう", post: "ふく" },
  { target: "復", pre: "おう", read: "ふく" },
  { target: "徳", pre: "どう", read: "とく" },
  { target: "志", read: "こころざし" },
  { target: "応", read: "おう", post: "えん" },
  { target: "快", read: "こころよ", post: "い" },
  { target: "性", read: "せい", post: "かく" },
  { target: "恩", read: "おん", post: "じん" },
  { target: "情", read: "じょう", post: "ほう" },
  { target: "態", read: "たい", post: "ど" },
  { target: "慣", read: "な", post: "れる" },
  { target: "承", read: "しょう", post: "ち" },
  { target: "技", read: "わざ" },
  { target: "招", read: "まね", post: "く" },
  { target: "授", read: "じゅ", post: "ぎょう" },
  { target: "採", read: "さい", post: "てん" },
  { target: "接", pre: "ちょく", read: "せつ" },
  { target: "提", read: "てい", post: "あん" },
  { target: "損", read: "そん" },
  { target: "支", read: "ささ", post: "える" },
  { target: "政", read: "せい", post: "じ" },
  { target: "故", pre: "じ", read: "こ" },
  { target: "敵", read: "てき" },
  { target: "断", read: "ことわ", post: "る" },
  { target: "旧", read: "きゅう", post: "しょうがつ" },
  { target: "易", pre: "ぼう", read: "えき" },
  { target: "暴", read: "あば", post: "れる" },
  { target: "条", read: "じょう", post: "けん" },
  { target: "枝", read: "えだ" },
  { target: "査", pre: "けん", read: "さ" },
  { target: "格", pre: "か", read: "かく" },
  { target: "桜", read: "さくら" },
  { target: "検", read: "けん", post: "さ" },
  { target: "構", read: "かま", post: "える" },
  { target: "武", read: "ぶ", post: "し" },
  { target: "比", read: "くら", post: "べる" },
  { target: "永", read: "えい", post: "えん" },
  { target: "河", read: "か", post: "せん" },
  { target: "液", read: "えき", post: "たい" },
  { target: "混", read: "ま", post: "ぜる" },
  { target: "減", read: "へ", post: "る" },
  { target: "測", read: "はか", post: "る" },
  { target: "準", read: "じゅん", post: "び" },
  { target: "演", read: "えん", post: "そう" },
  { target: "潔", pre: "せい", read: "けつ" },
  { target: "災", read: "さい", post: "がい" },
  { target: "燃", read: "も", post: "える" },
  { target: "版", pre: "しゅっ", read: "ぱん" },
  { target: "犯", read: "はん", post: "にん" },
  { target: "状", read: "じょう", post: "たい" },
  { target: "独", read: "どく", post: "りつ" },
  { target: "率", read: "ひき", post: "いる" },
  { target: "現", read: "あらわ", post: "れる" },
  { target: "留", read: "る", post: "すばん" },
  { target: "略", pre: "しょう", read: "りゃく" },
  { target: "益", pre: "り", read: "えき" },
  { target: "眼", read: "め", post: "がね" },
  { target: "破", read: "やぶ", post: "る" },
  { target: "確", read: "たし", post: "か" },
  { target: "示", read: "しめ", post: "す" },
  { target: "祖", read: "そ", post: "ふ" },
  { target: "禁", read: "きん", post: "し" },
  { target: "移", read: "うつ", post: "る" },
  { target: "程", read: "ほど" },
  { target: "税", read: "ぜい", post: "きん" },
  { target: "築", read: "きず", post: "く" },
  { target: "精", read: "せい", post: "しん" },
  { target: "素", read: "そ", post: "ざい" },
  { target: "経", read: "けい", post: "けん" },
  { target: "統", read: "とう", post: "いつ" },
  { target: "絶", read: "た", post: "える" },
  { target: "綿", read: "わた" },
  { target: "総", read: "そう", post: "ごう" },
  { target: "編", read: "あ", post: "む" },
  { target: "績", pre: "せい", read: "せき" },
  { target: "織", read: "お", post: "りもの" },
  { target: "罪", read: "つみ" },
  { target: "群", read: "む", post: "れ" },
  { target: "義", read: "ぎ", post: "む" },
  { target: "耕", read: "たがや", post: "す" },
  { target: "職", read: "しょく", post: "ぎょう" },
  { target: "肥", read: "こ", post: "える" },
  { target: "能", read: "のう", post: "りょく" },
  { target: "興", read: "きょう", post: "み" },
  { target: "舌", read: "した", post: "ざわり" },
  { target: "舎", pre: "こう", read: "しゃ" },
  { target: "術", pre: "げい", read: "じゅつ" },
  { target: "衛", read: "えい", post: "せい" },
  { target: "製", read: "せい", post: "ひん" },
  { target: "複", read: "ふく", post: "すう" },
  { target: "規", read: "き", post: "そく" },
  { target: "解", read: "と", post: "く" },
  { target: "設", read: "せっ", post: "けい" },
  { target: "許", read: "ゆる", post: "す" },
  { target: "証", read: "しょう", post: "めい" },
  { target: "評", read: "ひょう", post: "か" },
  { target: "講", read: "こう", post: "どう" },
  { target: "謝", read: "あやま", post: "る" },
  { target: "識", pre: "ち", read: "しき" },
  { target: "護", pre: "ほ", read: "ご" },
  { target: "豊", read: "ゆた", post: "か" },
  { target: "財", read: "ざい", post: "さん" },
  { target: "貧", read: "まず", post: "しい" },
  { target: "責", read: "せき", post: "にん" },
  { target: "貸", read: "か", post: "す" },
  { target: "貿", read: "ぼう", post: "えき" },
  { target: "賀", pre: "ねん", read: "が", post: "じょう" },
  { target: "資", read: "し", post: "りょう" },
  { target: "賛", read: "さん", post: "せい" },
  { target: "質", read: "しつ", post: "もん" },
  { target: "輸", read: "ゆ", post: "しゅつ" },
  { target: "述", read: "の", post: "べる" },
  { target: "迷", read: "まよ", post: "う" },
  { target: "退", read: "しりぞ", post: "く" },
  { target: "逆", read: "ぎゃく" },
  { target: "造", read: "ぞう", post: "せん" },
  { target: "過", read: "す", post: "ぎる" },
  { target: "適", read: "てき", post: "とう" },
  { target: "酸", read: "さん", post: "そ" },
  { target: "鉱", read: "こう", post: "ざん" },
  { target: "銅", read: "どう" },
  { target: "銭", read: "ぜに" },
  { target: "防", read: "ふせ", post: "ぐ" },
  { target: "限", read: "かぎ", post: "る" },
  { target: "険", read: "けわ", post: "しい" },
  { target: "際", pre: "こく", read: "さい" },
  { target: "雑", read: "ざっ", post: "し" },
  { target: "非", read: "ひ", post: "じょう" },
  { target: "預", read: "あず", post: "ける" },
  { target: "領", pre: "だいとう", read: "りょう" },
  { target: "額", read: "がく" },
  { target: "飼", read: "か", post: "いいぬ" },
];

export default words;
