/**
 * 6年生の漢字（181字）の出題語。方針は 1.ts と同じ。
 */

import type { KanjiWord } from "../types.ts";

const words: KanjiWord[] = [
  { target: "並", read: "なら", post: "ぶ" },
  { target: "乱", read: "みだ", post: "れる" },
  { target: "乳", pre: "ぎゅう", read: "にゅう" },
  { target: "亡", read: "な", post: "くなる" },
  { target: "仁", read: "じん" },
  { target: "供", pre: "てい", read: "きょう" },
  { target: "俳", read: "はい", post: "く" },
  { target: "値", read: "ね", post: "だん" },
  { target: "傷", read: "きず" },
  { target: "優", read: "やさ", post: "しい" },
  { target: "党", pre: "せい", read: "とう" },
  { target: "冊", read: "さつ" },
  { target: "処", read: "しょ", post: "り" },
  { target: "刻", read: "きざ", post: "む" },
  { target: "割", read: "わ", post: "る" },
  { target: "創", read: "そう", post: "りつ" },
  { target: "劇", read: "げき" },
  { target: "勤", read: "きん", post: "む" },
  { target: "危", read: "あぶ", post: "ない" },
  { target: "卵", read: "たまご" },
  { target: "厳", read: "きび", post: "しい" },
  { target: "収", read: "しゅう", post: "にゅう" },
  { target: "后", read: "こう", post: "ごう" },
  { target: "否", read: "ひ", post: "てい" },
  { target: "吸", read: "す", post: "う" },
  { target: "呼", read: "よ", post: "ぶ" },
  { target: "善", read: "ぜん" },
  { target: "困", read: "こま", post: "る" },
  { target: "垂", read: "た", post: "れる" },
  { target: "城", read: "しろ" },
  { target: "域", pre: "ち", read: "いき" },
  { target: "奏", pre: "えん", read: "そう" },
  { target: "奮", pre: "こう", read: "ふん" },
  { target: "姿", read: "すがた" },
  { target: "存", read: "そん", post: "ざい" },
  { target: "孝", read: "こう", post: "こう" },
  { target: "宅", read: "たく" },
  { target: "宇", read: "う", post: "ちゅう" },
  { target: "宗", read: "しゅう", post: "きょう" },
  { target: "宙", pre: "う", read: "ちゅう" },
  { target: "宝", read: "たから" },
  { target: "宣", read: "せん", post: "げん" },
  { target: "密", pre: "ひ", read: "みつ" },
  { target: "寸", read: "すん", post: "ぽう" },
  { target: "専", read: "せん", post: "もん" },
  { target: "射", pre: "はっ", read: "しゃ" },
  { target: "将", read: "しょう", post: "らい" },
  { target: "尊", read: "とうと", post: "い" },
  { target: "就", read: "しゅう", post: "しょく" },
  { target: "尺", read: "しゃく", post: "ど" },
  { target: "届", read: "とど", post: "く" },
  { target: "展", read: "てん", post: "らんかい" },
  { target: "層", pre: "ち", read: "そう" },
  { target: "己", pre: "じ", read: "こ", post: "しょうかい" },
  { target: "巻", read: "ま", post: "く" },
  { target: "幕", read: "まく" },
  { target: "干", read: "ほ", post: "す" },
  { target: "幼", read: "おさな", post: "い" },
  { target: "庁", pre: "けん", read: "ちょう" },
  { target: "座", read: "すわ", post: "る" },
  { target: "延", read: "の", post: "びる" },
  { target: "律", pre: "ほう", read: "りつ" },
  { target: "従", read: "したが", post: "う" },
  { target: "忘", read: "わす", post: "れる" },
  { target: "忠", read: "ちゅう", post: "じつ" },
  { target: "憲", read: "けん", post: "ぽう" },
  { target: "我", read: "われ" },
  { target: "批", read: "ひ", post: "はん" },
  { target: "担", read: "たん", post: "とう" },
  { target: "拝", read: "おが", post: "む" },
  { target: "拡", read: "かく", post: "だい" },
  { target: "捨", read: "す", post: "てる" },
  { target: "探", read: "さが", post: "す" },
  { target: "推", read: "すい", post: "り" },
  { target: "揮", pre: "はっ", read: "き" },
  { target: "操", read: "そう", post: "さ" },
  { target: "敬", read: "うやま", post: "う" },
  { target: "映", read: "えい", post: "が" },
  { target: "晩", read: "ばん", post: "ごはん" },
  { target: "暖", read: "だん", post: "ぼう" },
  { target: "暮", read: "く", post: "らす" },
  { target: "朗", read: "ろう", post: "どく" },
  { target: "机", read: "つくえ" },
  { target: "枚", read: "まい" },
  { target: "染", read: "そ", post: "める" },
  { target: "株", read: "かぶ" },
  { target: "棒", read: "ぼう" },
  { target: "模", read: "も", post: "けい" },
  { target: "権", read: "けん", post: "り" },
  { target: "樹", read: "じゅ", post: "もく" },
  { target: "欲", read: "ほ", post: "しい" },
  { target: "段", pre: "かい", read: "だん" },
  { target: "沿", read: "そ", post: "う" },
  { target: "泉", read: "いずみ" },
  { target: "洗", read: "あら", post: "う" },
  { target: "派", pre: "りっ", read: "ぱ" },
  { target: "済", pre: "けい", read: "ざい" },
  { target: "源", pre: "し", read: "げん" },
  { target: "潮", read: "しお", post: "かぜ" },
  { target: "激", read: "はげ", post: "しい" },
  { target: "灰", read: "はい", post: "いろ" },
  { target: "熟", read: "じゅく", post: "ご" },
  { target: "片", read: "かた", post: "づける" },
  { target: "班", read: "はん" },
  { target: "異", read: "こと", post: "なる" },
  { target: "疑", read: "うたが", post: "う" },
  { target: "痛", read: "いた", post: "い" },
  { target: "皇", read: "こう", post: "たいし" },
  { target: "盛", read: "も", post: "る" },
  { target: "盟", pre: "どう", read: "めい" },
  { target: "看", read: "かん", post: "ごし" },
  { target: "砂", read: "すな" },
  { target: "磁", read: "じ", post: "しゃく" },
  { target: "私", read: "わたし" },
  { target: "秘", read: "ひ", post: "みつ" },
  { target: "穀", read: "こく", post: "もつ" },
  { target: "穴", read: "あな" },
  { target: "窓", read: "まど" },
  { target: "筋", read: "きん", post: "にく" },
  { target: "策", pre: "たい", read: "さく" },
  { target: "簡", read: "かん", post: "たん" },
  { target: "糖", pre: "さ", read: "とう" },
  { target: "系", read: "けい", post: "とう" },
  { target: "紅", read: "こう", post: "ちゃ" },
  { target: "納", pre: "しゅう", read: "のう" },
  { target: "純", read: "じゅん", post: "すい" },
  { target: "絹", read: "きぬ" },
  { target: "縦", read: "たて" },
  { target: "縮", read: "ちぢ", post: "む" },
  { target: "署", pre: "けいさつ", read: "しょ" },
  { target: "翌", read: "よく", post: "じつ" },
  { target: "聖", read: "せい", post: "しょ" },
  { target: "肺", read: "はい", post: "かつりょう" },
  { target: "背", read: "せ", post: "なか" },
  { target: "胸", read: "むね" },
  { target: "脳", pre: "だい", read: "のう" },
  { target: "腹", read: "はら" },
  { target: "臓", pre: "しん", read: "ぞう" },
  { target: "臨", read: "りん", post: "じ" },
  { target: "至", read: "いた", post: "る" },
  { target: "若", read: "わか", post: "い" },
  { target: "著", read: "ちょ", post: "しゃ" },
  { target: "蒸", read: "む", post: "す" },
  { target: "蔵", pre: "れい", read: "ぞう", post: "こ" },
  { target: "蚕", read: "かいこ" },
  { target: "衆", pre: "たい", read: "しゅう" },
  { target: "裁", read: "さい", post: "ばん" },
  { target: "装", pre: "ふく", read: "そう" },
  { target: "裏", read: "うら" },
  { target: "補", read: "おぎな", post: "う" },
  { target: "視", read: "し", post: "りょく" },
  { target: "覧", pre: "てん", read: "らん", post: "かい" },
  { target: "討", read: "とう", post: "ろん" },
  { target: "訪", read: "おとず", post: "れる" },
  { target: "訳", read: "やく" },
  { target: "詞", pre: "か", read: "し" },
  { target: "誌", pre: "ざっ", read: "し" },
  { target: "認", read: "みと", post: "める" },
  { target: "誕", read: "たん", post: "じょうび" },
  { target: "誠", read: "せい", post: "じつ" },
  { target: "誤", read: "ご", post: "かい" },
  { target: "論", read: "ろん" },
  { target: "諸", read: "しょ", post: "こく" },
  { target: "警", read: "けい", post: "さつ" },
  { target: "貴", read: "き", post: "ちょう" },
  { target: "賃", pre: "うん", read: "ちん" },
  { target: "遺", read: "い", post: "さん" },
  { target: "郵", read: "ゆう", post: "びん" },
  { target: "郷", pre: "こ", read: "きょう" },
  { target: "針", read: "はり" },
  { target: "鋼", pre: "てっ", read: "こう" },
  { target: "閉", read: "と", post: "じる" },
  { target: "閣", pre: "ない", read: "かく" },
  { target: "降", read: "ふ", post: "る" },
  { target: "陛", read: "へい", post: "か" },
  { target: "除", read: "のぞ", post: "く" },
  { target: "障", pre: "こ", read: "しょう" },
  { target: "難", read: "むずか", post: "しい" },
  { target: "革", read: "かく", post: "めい" },
  { target: "頂", read: "いただ", post: "く" },
  { target: "骨", read: "ほね" },
];

export default words;
