/**
 * 検証用の参照表を生成する one-off スクリプト。
 *
 *   deno task gen:readings   # → tools/kanji_readings.ts
 *
 * 出力は「漢字 → 辞書上の読み」の表で、**出題データそのものではない**。
 * words_test.ts が「手で書いた語の読みが、その漢字の読みとして実在するか」を
 * 機械的に確かめるためだけに使う（誤記・取り違えの検出）。クライアントには
 * 含まれない。
 *
 * 学年（配当表）も併せて出力し、学年網羅のテストに使う。2020年度改訂で第4
 * 学年に加わった都道府県漢字20字はデータセットの grade に無いため明示する。
 *
 * データ源: davidluzgouveia/kanji-data（KANJIDIC 由来、GitHub raw）。
 */

const CACHE = new URL("./.cache/kanji-data.json", import.meta.url);
const OUT = new URL("./kanji_readings.ts", import.meta.url);
const SRC =
  "https://raw.githubusercontent.com/davidluzgouveia/kanji-data/master/kanji.json";
const UA = "kids-study readings generator (github.com/kuboon/kids-study)";

/** 2020年度実施の学年別漢字配当表で第4学年に加わった都道府県漢字。 */
export const PREFECTURE_GRADE4 = [
  ..."茨媛岡潟岐熊香佐埼崎滋鹿縄井沖栃奈梨阪阜",
] as const;

type Entry = {
  grade: number | null;
  readings_on: string[];
  readings_kun: string[];
};

const fetchData = async (): Promise<Record<string, Entry>> => {
  try {
    return JSON.parse(await Deno.readTextFile(CACHE));
  } catch { /* not cached yet */ }
  const res = await fetch(SRC, { headers: { "user-agent": UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching kanji data`);
  const text = await res.text();
  await Deno.mkdir(new URL("./.cache/", import.meta.url), { recursive: true });
  await Deno.writeTextFile(CACHE, text);
  return JSON.parse(text);
};

const main = async () => {
  const data = await fetchData();

  const grades: string[][] = Array.from({ length: 6 }, () => []);
  for (const [ch, e] of Object.entries(data)) {
    if (e.grade && e.grade >= 1 && e.grade <= 6) grades[e.grade - 1].push(ch);
  }
  for (const ch of PREFECTURE_GRADE4) {
    if (!grades.some((g) => g.includes(ch))) grades[3].push(ch);
  }
  for (const g of grades) {
    g.sort((a, b) => a.codePointAt(0)! - b.codePointAt(0)!);
  }

  // 読みは "およ.ぐ" 形式（. の前が漢字の読み、後が送り仮名）と、
  // 送り仮名のない "みぎ"、音読み "こう" が混在する。そのまま持つ。
  const all = grades.flat();
  const lines = all.map((ch) => {
    const e = data[ch];
    const kun = (e.readings_kun ?? []).map((s) => s.replace(/-/g, "")).filter(
      Boolean,
    );
    const on = (e.readings_on ?? []).map((s) => s.replace(/-/g, "")).filter(
      Boolean,
    );
    return `  ${JSON.stringify(ch)}: { kun: ${JSON.stringify(kun)}, on: ${
      JSON.stringify(on)
    } },`;
  });

  await Deno.writeTextFile(
    OUT,
    `// AUTO-GENERATED by tools/gen_kanji_readings.ts. DO NOT EDIT.
// 検証専用の参照表（KANJIDIC 由来 / davidluzgouveia/kanji-data）。
// 出題データではなく、quiz/kanji/words_test.ts が手書きの語データを
// 突き合わせて誤記を検出するために読む。クライアントには含まれない。

/** 学年別漢字配当表（1〜6年）。添字0が1年生。2020年度改訂の都道府県漢字を含む。 */
export const GRADE_KANJI: readonly string[] = [
${
      grades.map((g, i) =>
        `  // ${i + 1}年 (${g.length}字)\n  ${JSON.stringify(g.join(""))},`
      ).join("\n")
    }
];

/** 漢字 → 辞書上の読み。kun は "およ.ぐ" のように送り仮名を . で区切る。 */
export const KANJI_READINGS: Record<
  string,
  { kun: readonly string[]; on: readonly string[] }
> = {
${lines.join("\n")}
};
`,
  );
  console.log(
    `wrote ${all.length} kanji → tools/kanji_readings.ts (${
      grades.map((g) => g.length).join("/")
    })`,
  );
};

if (import.meta.main) await main();
