/**
 * One-off generator: fetch each grade kanji's KanjiVG SVG and write its
 * per-stroke render paths to `quiz/stroke/kanji_paths.ts`. Run locally (needs
 * network); the generated file is committed so CI never fetches.
 *
 *   deno task gen:strokes              # all grade kanji → write the .ts
 *   deno run -A tools/gen_kanji_strokes.ts --dry 大 一 小   # print only
 *
 * Data source: KanjiVG (https://kanjivg.tagaini.net), (C) Ulrich Apel,
 * licensed CC BY-SA 3.0. The extracted path data is likewise CC BY-SA 3.0.
 */

import { GRADE_WORDS } from "../quiz/kanji/words/mod.ts";

const CACHE_DIR = new URL("./.cache/kanjivg/", import.meta.url);
const OUT_PATHS = new URL("../quiz/stroke/kanji_paths.ts", import.meta.url);
const RAW_BASE =
  "https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/";
const UA = "kids-study stroke generator (github.com/kuboon/kids-study)";

/** Ordered stroke render paths (SVG "d") from one KanjiVG SVG. */
export const svgPaths = (svg: string): string[] => {
  const tags = svg.match(/<path\b[^>]*>/g) ?? [];
  const out: string[] = [];
  for (const tag of tags) {
    const d = tag.match(/\bd="([^"]+)"/)?.[1];
    if (d) out.push(d);
  }
  return out;
};

// ---- fetch with cache ------------------------------------------------------

const codeToFile = (ch: string) =>
  ch.codePointAt(0)!.toString(16).padStart(5, "0") + ".svg";

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/** Returns SVG text, or null if KanjiVG has no such file (404). */
const fetchSvg = async (ch: string): Promise<string | null> => {
  const file = codeToFile(ch);
  const cached = new URL(file, CACHE_DIR);
  try {
    return await Deno.readTextFile(cached);
  } catch { /* not cached yet */ }

  let delay = 500;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch(RAW_BASE + file, {
        headers: { "user-agent": UA },
      });
      if (res.status === 404) {
        await res.body?.cancel();
        return null;
      }
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const text = await res.text();
      await Deno.mkdir(CACHE_DIR, { recursive: true });
      await Deno.writeTextFile(cached, text);
      await sleep(100); // be polite to raw.githubusercontent
      return text;
    } catch (e) {
      if (attempt === 2) throw e;
      await sleep(delay);
      delay *= 2;
    }
  }
  return null;
};

// ---- collect target chars --------------------------------------------------

const collectChars = (): string[] => {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const words of GRADE_WORDS) {
    for (const w of words) {
      if (!seen.has(w.target)) {
        seen.add(w.target);
        out.push(w.target);
      }
    }
  }
  return out;
};

// ---- main ------------------------------------------------------------------

const main = async () => {
  const args = Deno.args.filter((a) => a !== "--dry");
  const dry = Deno.args.includes("--dry");
  const chars = args.length > 0 ? args : collectChars();

  const pathData: Record<string, string[]> = {};
  const missing: string[] = [];
  for (const ch of chars) {
    const svg = await fetchSvg(ch);
    const paths = svg ? svgPaths(svg) : [];
    if (paths.length === 0) {
      missing.push(ch);
      continue;
    }
    pathData[ch] = paths;
    console.log(`${ch} ${codeToFile(ch)}: ${paths.length} strokes`);
  }
  if (missing.length) {
    console.warn(
      `\n%c${missing.length} skipped (no KanjiVG / no strokes): ${
        missing.join("")
      }`,
      "color:orange",
    );
  }

  if (dry) {
    console.log(
      `\n(dry run, ${Object.keys(pathData).length} chars, not written)`,
    );
    return;
  }

  const keys = Object.keys(pathData).sort((a, b) =>
    a.codePointAt(0)! - b.codePointAt(0)!
  );
  const lines = keys.map((ch) => {
    const ds = pathData[ch].map((d) => JSON.stringify(d)).join(", ");
    return `  ${JSON.stringify(ch)}: [${ds}],`;
  });
  await Deno.writeTextFile(
    OUT_PATHS,
    `// AUTO-GENERATED by tools/gen_kanji_strokes.ts. DO NOT EDIT.
// Derived from KanjiVG (https://kanjivg.tagaini.net), (C) Ulrich Apel,
// licensed CC BY-SA 3.0. This derived data is likewise CC BY-SA 3.0.
// See /NOTICE.
//
// Each value is the list of KanjiVG stroke paths (SVG path "d", 109x109
// viewBox) in writing order, used both to draw the kanji one stroke at a time
// and to fuzzy-match the player's drawn strokes.

export const KANJI_PATHS: Record<string, readonly string[]> = {
${lines.join("\n")}
};
`,
  );
  console.log(`\nwrote ${keys.length} chars → kanji_paths.ts`);
};

if (import.meta.main) await main();
