/**
 * Hand-curated prompt overrides for the kanji-writing game, consumed only by
 * `tools/gen_kanji_words.ts` (NOT shipped to the client). Auto-generated
 * prompts pick a kanji's first reading from the dataset, which is fine for most
 * kanji but ambiguous or obscure for some (同音異字, rare kun readings). Any
 * kanji listed here uses this prompt instead; everything else falls back to the
 * dataset reading. Edit freely to improve prompt quality.
 */

import type { WriteWord } from "../quiz/stroke/word_types.ts";

/**
 * 都道府県名などに用いる20字。2020年度実施の学年別漢字配当表で第4学年に追加
 * された（それ以前は中学校で学ぶ配当だったため、多くの漢字データセットでは
 * grade が 1〜6 に入っていない）。ここで明示的に第4学年へ含める。
 */
export const PREFECTURE_GRADE4 = [
  ..."茨媛岡潟岐熊香佐埼崎滋鹿縄井沖栃奈梨阪阜",
] as const;

export const OVERRIDES: Record<string, WriteWord> = {
  "大": { kanji: "大", read: "おお", post: "きい" },
  "小": { kanji: "小", read: "ちい", post: "さい" },
  "上": { kanji: "上", read: "うえ" },
  "下": { kanji: "下", read: "した" },
  "出": { kanji: "出", read: "で", post: "ぐち" },
  "入": { kanji: "入", read: "はい", post: "る" },
  "立": { kanji: "立", read: "た", post: "つ" },
  "見": { kanji: "見", read: "み", post: "る" },
  "休": { kanji: "休", read: "やす", post: "む" },
  "早": { kanji: "早", read: "はや", post: "おき" },
  "正": { kanji: "正", read: "ただ", post: "しい" },
  "生": { kanji: "生", read: "い", post: "きる" },
  "学": { kanji: "学", read: "まな", post: "ぶ" },
  "青": { kanji: "青", read: "あお", post: "い" },
  "赤": { kanji: "赤", read: "あか", post: "い" },
  "白": { kanji: "白", read: "しろ", post: "い" },
  "歌": { kanji: "歌", read: "うた" },
  "回": { kanji: "回", read: "まわ", post: "る" },
  "会": { kanji: "会", read: "かい", post: "しゃ" },
  "楽": { kanji: "楽", read: "たの", post: "しい" },
  "強": { kanji: "強", read: "つよ", post: "い" },
  "教": { kanji: "教", read: "おし", post: "える" },
  "近": { kanji: "近", read: "ちか", post: "い" },
  "古": { kanji: "古", read: "ふる", post: "い" },
  "広": { kanji: "広", read: "ひろ", post: "い" },
  "光": { kanji: "光", read: "ひか", post: "る" },
  "考": { kanji: "考", read: "かんが", post: "える" },
  "高": { kanji: "高", read: "たか", post: "い" },
  "黒": { kanji: "黒", read: "くろ", post: "い" },
  "細": { kanji: "細", read: "ほそ", post: "い" },
  "作": { kanji: "作", read: "つく", post: "る" },
  "思": { kanji: "思", read: "おも", post: "う" },
  "弱": { kanji: "弱", read: "よわ", post: "い" },
  "書": { kanji: "書", read: "か", post: "きとり" },
  "食": { kanji: "食", read: "た", post: "べる" },
  "新": { kanji: "新", read: "あたら", post: "しい" },
  "走": { kanji: "走", read: "はし", post: "る" },
  "長": { kanji: "長", read: "なが", post: "い" },
  "読": { kanji: "読", read: "よ", post: "む" },
  "買": { kanji: "買", pre: "お", read: "か", post: "いもの" },
  "売": { kanji: "売", read: "う", post: "る" },
  "話": { kanji: "話", read: "はなし" },
  "歩": { kanji: "歩", read: "ある", post: "く" },
  "明": { kanji: "明", read: "あか", post: "るい" },
  "帰": { kanji: "帰", read: "かえ", post: "りみち" },
  "悪": { kanji: "悪", read: "わる", post: "い" },
  "暗": { kanji: "暗", read: "くら", post: "い" },
  "育": { kanji: "育", read: "そだ", post: "てる" },
  "飲": { kanji: "飲", read: "の", post: "む" },
  "泳": { kanji: "泳", read: "およ", post: "ぐ" },
  "寒": { kanji: "寒", read: "さむ", post: "い" },
  "急": { kanji: "急", read: "いそ", post: "ぐ" },
  "苦": { kanji: "苦", read: "くる", post: "しい" },
  "軽": { kanji: "軽", read: "かる", post: "い" },
  "決": { kanji: "決", read: "き", post: "める" },
  "幸": { kanji: "幸", read: "しあわ", post: "せ" },
  "死": { kanji: "死", read: "し", post: "ぬ" },
  "使": { kanji: "使", read: "つか", post: "う" },
  "始": { kanji: "始", read: "はじ", post: "める" },
  "持": { kanji: "持", read: "も", post: "つ" },
  "守": { kanji: "守", read: "まも", post: "る" },
  "拾": { kanji: "拾", read: "ひろ", post: "う" },
  "終": { kanji: "終", read: "お", post: "わる" },
  "習": { kanji: "習", read: "なら", post: "う" },
  "集": { kanji: "集", read: "あつ", post: "める" },
  "重": { kanji: "重", read: "おも", post: "い" },
  "助": { kanji: "助", read: "たす", post: "ける" },
  "勝": { kanji: "勝", read: "か", post: "つ" },
  "乗": { kanji: "乗", read: "の", post: "る" },
  "深": { kanji: "深", read: "ふか", post: "い" },
  "進": { kanji: "進", read: "すす", post: "む" },
  "待": { kanji: "待", read: "ま", post: "つ" },
  "短": { kanji: "短", read: "みじか", post: "い" },
  "登": { kanji: "登", read: "のぼ", post: "る" },
  "動": { kanji: "動", read: "うご", post: "く" },
  "配": { kanji: "配", read: "くば", post: "る" },
  "悲": { kanji: "悲", read: "かな", post: "しい" },
  "美": { kanji: "美", read: "うつく", post: "しい" },
  "遊": { kanji: "遊", read: "あそ", post: "ぶ" },
  "落": { kanji: "落", read: "お", post: "ちる" },
  "覚": { kanji: "覚", read: "おぼ", post: "える" },
  "省": { kanji: "省", read: "はぶ", post: "く" },
  "連": { kanji: "連", read: "れん", post: "らく" },
  "散": { kanji: "散", read: "ち", post: "る" },
  "治": { kanji: "治", read: "なお", post: "る" },
  "折": { kanji: "折", read: "お", post: "りがみ" },
  "焼": { kanji: "焼", read: "や", post: "く" },
  "積": { kanji: "積", read: "つ", post: "もる" },
  "続": { kanji: "続", read: "つづ", post: "ける" },
  "包": { kanji: "包", read: "つつ", post: "む" },
  "浴": { kanji: "浴", read: "あ", post: "びる" },
  "結": { kanji: "結", read: "むす", post: "ぶ" },
  "老": { kanji: "老", read: "お", post: "いる" },
  "競": { kanji: "競", read: "きそ", post: "う" },
  "営": { kanji: "営", read: "いとな", post: "む" },
  "喜": { kanji: "喜", read: "よろこ", post: "ぶ" },
  "許": { kanji: "許", read: "ゆる", post: "す" },
  "経": { kanji: "経", read: "けい", post: "けん" },
  "険": { kanji: "険", read: "けわ", post: "しい" },
  "限": { kanji: "限", read: "かぎ", post: "る" },
  "耕": { kanji: "耕", read: "たがや", post: "す" },
  "構": { kanji: "構", read: "かま", post: "える" },
  "混": { kanji: "混", read: "ま", post: "ぜる" },
  "増": { kanji: "増", read: "ふ", post: "える" },
  "述": { kanji: "述", read: "の", post: "べる" },
  "招": { kanji: "招", read: "まね", post: "く" },
  "設": { kanji: "設", read: "せっ", post: "けい" },
  "貸": { kanji: "貸", read: "か", post: "す" },
  "断": { kanji: "断", read: "ことわ", post: "る" },
  "築": { kanji: "築", read: "きず", post: "く" },
  "燃": { kanji: "燃", read: "も", post: "える" },
  "破": { kanji: "破", read: "やぶ", post: "る" },
  "貧": { kanji: "貧", read: "まず", post: "しい" },
  "編": { kanji: "編", read: "あ", post: "む" },
  "保": { kanji: "保", read: "たも", post: "つ" },
  "豊": { kanji: "豊", read: "ゆた", post: "か" },
  "迷": { kanji: "迷", read: "まよ", post: "う" },
  "預": { kanji: "預", read: "あず", post: "ける" },
  "映": { kanji: "映", read: "えい", post: "が" },
  "延": { kanji: "延", read: "えん", post: "き" },
  "割": { kanji: "割", read: "わ", post: "る" },
  "干": { kanji: "干", read: "ほ", post: "す" },
  "危": { kanji: "危", read: "あぶ", post: "ない" },
  "疑": { kanji: "疑", read: "うたが", post: "う" },
  "吸": { kanji: "吸", read: "す", post: "う" },
  "敬": { kanji: "敬", read: "うやま", post: "う" },
  "激": { kanji: "激", read: "はげ", post: "しい" },
  "厳": { kanji: "厳", read: "きび", post: "しい" },
  "呼": { kanji: "呼", read: "よ", post: "ぶ" },
  "誤": { kanji: "誤", read: "ご", post: "かい" },
  "刻": { kanji: "刻", read: "きざ", post: "む" },
  "困": { kanji: "困", read: "こま", post: "る" },
  "捨": { kanji: "捨", read: "す", post: "てる" },
  "若": { kanji: "若", read: "わか", post: "い" },
  "縮": { kanji: "縮", read: "ちぢ", post: "む" },
  "洗": { kanji: "洗", read: "あら", post: "う" },
  "探": { kanji: "探", read: "さが", post: "す" },
  "頂": { kanji: "頂", read: "いただ", post: "く" },
  "痛": { kanji: "痛", read: "いた", post: "い" },
  "届": { kanji: "届", read: "とど", post: "く" },
  "難": { kanji: "難", read: "むずか", post: "しい" },
  "認": { kanji: "認", read: "みと", post: "める" },
  "拝": { kanji: "拝", read: "おが", post: "む" },
  "並": { kanji: "並", read: "なら", post: "ぶ" },
  "補": { kanji: "補", read: "おぎな", post: "う" },
  "忘": { kanji: "忘", read: "わす", post: "れる" },
  "優": { kanji: "優", read: "やさ", post: "しい" },
  "幼": { kanji: "幼", read: "おさな", post: "い" },
  "欲": { kanji: "欲", read: "ほ", post: "しい" },
  // 都道府県漢字のうち、データセットの第一読みが obscure なものを補正。
  "奈": { kanji: "奈", read: "な" }, // 奈良（いかん/からなし は難しい）
  "埼": { kanji: "埼", read: "さい" }, // 埼玉（崎 と読みが被らないように）
};
