name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  pull-requests: write
  id-token: write

jobs:
  deploy:
    uses: kuboon/workflows/.github/workflows/github-page-with-preview.yaml@main
    with:
      build-command: mise run build
      dist-dir: dist
